package leasecity.dto.user;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import leasecity.dto.lease.LeaseCall;
import leasecity.dto.lease.LeaseDirectCall;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * 건설업체 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@EqualsAndHashCode(callSuper=false)
@Data
@AllArgsConstructor
public class ConstructionCompany extends User implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 연매출. */
	private Double yearlySale;

	/** 연 수주량. */
	private Integer yearlyAoor;

	/** 회사 규모. */
	private String companySize;

	/** 회사 분야. */
	private String companyCategory;

	/** 임대요청 목록. */
	private List<LeaseCall> leaseCallsList;

	/** 임대 직접신청 목록. */
	private List<LeaseDirectCall> leaseDirectCallsList;

	/** 자격증 목록. */
	private List<License> licenseList;

	/**
	 * 생성자.
	 */
	public ConstructionCompany() {
		super();
		this.leaseCallsList = new ArrayList<LeaseCall>();
		this.leaseDirectCallsList = new ArrayList<LeaseDirectCall>();
		this.licenseList = new ArrayList<License>();
	}
	
	public ConstructionCompany
			(	User user,
				Double yearlySale, Integer yearlyAoor,
				String companySize, String companyCategory){
		super(user);
		
		this.yearlySale = yearlySale;
		this.yearlyAoor = yearlyAoor;
		this.companySize = companySize;
		this.companyCategory = companyCategory;
		
		this.leaseCallsList = new ArrayList<LeaseCall>();
		this.leaseDirectCallsList = new ArrayList<LeaseDirectCall>();
		this.licenseList = new ArrayList<License>();
	}
	
	/*public ConstructionCompany(ConstructionCompany CC) {
		super(CC);

		this.yearlySale = CC.yearlySale;
		this.yearlyAoor = CC.yearlyAoor;
		this.companySize = CC.companySize;
		this.companyCategory = CC.companyCategory;

		this.leaseCallsList = new ArrayList<LeaseCall>();
		this.leaseDirectCallsList = new ArrayList<LeaseDirectCall>();
		this.licenseList = new ArrayList<License>();
	}*/

	
	/**
	 * UserId도 같이 출력되게 임의 설정
	 */
	@Override
	public String toString() {
		return "ConstructionCompany(userId="+ getUserId() +", yearlySale=" + yearlySale + ", yearlyAoor=" + yearlyAoor + ", companySize="
				+ companySize + ", companyCategory=" + companyCategory + ")";
	}	

}
