package leasecity.dto.user;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import leasecity.dto.lease.LeaseRequest;
import leasecity.dto.lease.LeaseTransfer;
import lombok.AllArgsConstructor;
import lombok.Data;

/**
 * 중장비 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@AllArgsConstructor
public class HeavyEquipment implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 차량번호. */
	private String idNumber;

	/** 회원. */
	private User users;

	/** 중장비 종류. */
	private String equipmentCategory;

	/** 임대신청 목록. */
	private List<LeaseRequest> leaseRequestsList;

	/** 임대양도 목록. */
	private List<LeaseTransfer> leaseTransferList;

	/**
	 * 생성자.
	 */
	public HeavyEquipment() {
		this.leaseRequestsList = new ArrayList<LeaseRequest>();
		this.leaseTransferList = new ArrayList<LeaseTransfer>();
	}
}
