package leasecity.dto.lease;

import java.io.Serializable;
import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * 임대신청 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode
public class LeaseRequest implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 임대 신청 번호. */
	private Integer leaseRequestNo;

	/** 임대 요청 번호. */
	private Integer leaseCallNo;
	
	/** 줃장비 차량 종류 */
	private String equipmentCategory;
	
	/** 중장비. 차 번호 */
	private String idNumber;

	/** 회원. */
	private String userId;
	
	/** 업체명 (DTO에서만 존재) */
	private String companyName;
	
	/** 대표자명 (DTO에서만 존재) */
	private String representName;

	/** 시작날짜(~부터). */
	private Date fromDate;

	/** 종료날짜(~까지). */
	private Date toDate;

	/** 선정날짜. */
	private Date regDate;

	/** 비용. */
	private Integer price;

	
	public LeaseRequest(Integer leaseCallNo, 
			String idNumber, String userId, 
			Date fromDate, Date toDate,	Integer price) {
		this.leaseCallNo = leaseCallNo;
		this.idNumber = idNumber;
		this.userId = userId;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.price = price;
	}
	
	
	

}
