package leasecity.dto.lease;

import java.io.Serializable;
import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * 임대신청 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode
public class LeaseRequest implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 임대 신청 번호. */
	private Integer leaseRequestNo;

	/** 임대 요청 번호. */
	private Integer leaseCallNo;
	
	/** 중장비. 차 번호 */
	private String idNumber;

	/** 회원. */
	private String userId;

	/** 시작날짜(~부터). */
	private Date fromDate;

	/** 종료날짜(~까지). */
	private Date toDate;

	/** 선정날짜. */
	private Date regDate;

	/** 비용. */
	private Integer price;

}
