package leasecity.dto.lease;

import java.io.Serializable;
import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * 임대선정 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode
public class LeaseSelection implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 임대 선정 번호. */
	private Integer leaseSelectionNo;

	/** 임대 요청 번호. */
	private Integer leaseCallNo;

	/** 임대 직접 요청 번호. */
	private Integer leaseDirectNo;

	/** 임대 신청 번호. */
	private Integer leaseRequestNo;

	/** 차량번호. */
	private String idNumber;

	/** 아이디. */
	private String userId;

	/** 중기업체 아이디. */
	private String equipmentId;

	/** 시작날짜(~부터). */
	private Date fromDate;

	/** 종료날짜(~까지). */
	private Date toDate;

	/** 선정날짜. */
	private Date regDate;

	/** 비용. */
	private Integer price;

}
