package leasecity.dto.adminwork;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 관리자 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class LeasecityAdmin implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 관리자 ID. */
	private String adminId;

	/** 관리자 비밀번호. */
	private String adminPass;

}
