package leasecity.dto.adminwork;

import java.io.Serializable;
import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * 알림 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@EqualsAndHashCode
@AllArgsConstructor
@NoArgsConstructor
public class Notify implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 알림번호. */
	private Integer notifyNo;

	/** 회원. */
	private String userId;

	/** 임대 요청 번호. */
	private Integer leaseCallNo;

	/** 임대 직접 요청 번호. */
	private Integer leaseDirectNo;

	/** 임대 신청 번호. */
	private Integer leaseRequestNo;

	/** 임대 선정 번호. */
	private Integer leaseSelectionNo;

	/** 임대 양도 번호. */
	private Integer leaseTransferNo;
	
	/** 글 속성 : 게시글 / 댓글 or 질문/답변 */
	private String attribute;

	/** 게시글 번호. */
	private Integer commentNo;

	/** 댓글 인식번호. */
	private Integer replyNo;

	/** 알림날짜. */
	private Date notifyDate;
	
	/** 알림링크. */
	private String notifyLink;
	
	/** 알림체크. */
	private String notifyCheck = "N";
}
