package leasecity.dto.community;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.StringTokenizer;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * 커뮤니티 게시글 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@EqualsAndHashCode
@AllArgsConstructor
@NoArgsConstructor
public class Comment implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 게시글 번호. */
	private Integer commentNo;
	
	/** 게시판에 찍히는 번호 */
	private Integer commentRowNum;

	/** 회원. */
	private String userId;
	
	/** 게시글 회원 업체명*/
	private String companyName;

	/** 게시글 제목. */
	private String commentTitle;

	/** 게시글 분류. 형식 -> 지역/종류  */
	private String commentCategory;
	
	/** 게시글 분류 : 지역 */
	private String locale;
	/** 게시글 분류 : 종류 */
	private String kind;

	/** 게시글 내용. */
	private String commentContent;

	/** 조회 수. */
	private Integer hits;

	/** 게시글 날짜. */
	private Date regDate;

	/** 게시글에 달린 총 댓글 개수 */
	private Integer replyCount;
	
	public Comment(Integer commentNo, String userId, 
			String commentTitle, String locale, String kind,
			String commentContent, Integer hits, Date regDate) {
		this.commentNo = commentNo;
		this.userId = userId;
		this.commentTitle = commentTitle;
		this.locale = locale;
		this.kind = kind;
		this.commentCategory = locale + "/" + kind;
		this.commentContent = commentContent;
		this.hits = hits;
		this.regDate = regDate;
	}

	public Comment(Integer commentNo, String userId, 
			String commentTitle, String commentCategory, 
			String commentContent, Integer hits, Date regDate) {
		this.commentNo = commentNo;
		this.userId = userId;
		this.commentTitle = commentTitle;
		this.commentCategory = commentCategory;
		this.commentContent = commentContent;
		this.hits = hits;
		this.regDate = regDate;
	}
	public Comment(String locale){
		this.locale=locale;
	}
	
	

}
