package leasecity.dto;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import lombok.Data;

import lombok.AllArgsConstructor;

/**
 * 건설업체 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@AllArgsConstructor
public class ConstructionCompany implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 회원. */
	private Users users;

	/** 연매출. */
	private Float yearlySale;

	/** 연 수주량. */
	private Integer yearlyAmountOfOrdersReceived;

	/** 회사 규모. */
	private String companySize;

	/** 회사 분야. */
	private String companyCategory;

	/** 임대요청 목록. */
	private Set<LeaseCalls> leaseCallsSet;

	/** 임대 직접신청 목록. */
	private Set<LeaseDirectCalls> leaseDirectCallsSet;

	/** 자격증 목록. */
	private Set<License> licenseSet;

	/**
	 * 생성자.
	 */
	public ConstructionCompany() {
		this.leaseCallsSet = new HashSet<LeaseCalls>();
		this.leaseDirectCallsSet = new HashSet<LeaseDirectCalls>();
		this.licenseSet = new HashSet<License>();
	}

}
