package leasecity.dto;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import lombok.AllArgsConstructor;
import lombok.Data;

/**
 * 중기업체 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@AllArgsConstructor
public class HeavyEquipmentCompany implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 회원. */
	private Users users;

	/** 도움요청 여부. */
	private String helpOnOff;

	/** 정보공개 여부. */
	private String infoOnOff;

	/** 중장비 목록. */
	private Set<HeavyEquipment> heavyEquipmentSet;

	/** 임대 직접신청 목록. */
	private Set<LeaseDirectCalls> leaseDirectCallsSet;

	/** 임대신청 목록. */
	private Set<LeaseRequests> leaseRequestsSet;

	/** 임대양도 목록. */
	private Set<LeaseTransfer> leaseTransferSet;

	/**
	 * 생성자.
	 */
	public HeavyEquipmentCompany() {
		this.heavyEquipmentSet = new HashSet<HeavyEquipment>();
		this.leaseDirectCallsSet = new HashSet<LeaseDirectCalls>();
		this.leaseRequestsSet = new HashSet<LeaseRequests>();
		this.leaseTransferSet = new HashSet<LeaseTransfer>();
	}
}
