package leasecity.dto;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 임대양도 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class LeaseTransfer implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 임대 양도 번호. */
	private Integer leaseTransferNo;

	/** 회원. */
	private Users users;

	/** 중장비. */
	private HeavyEquipment heavyEquipment;

	/** 중장비 종류. */
	private String equipmentCategory;

	/** 작업 장소. */
	private String address;

	/** 시작 날짜 (~부터). */
	private Date fromDate;

	/** 종료 날짜 (~까지). */
	private Date toDate;

	/** 비용. */
	private Integer price;

}
