package leasecity.dto;

import java.io.Serializable;
import java.util.Set;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 임대 직접신청 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class LeaseDirectCalls implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 임대 직접 신청 번호. */
	private Integer leaseDirectNo;

	/** 회원. */
	private Users constructIdusers;

	/** 회원. */
	private Users users;

	/** 임대요청. */
	private LeaseCalls leaseCalls;

	/** 요청 제목. */
	private String callName;

	/** 직접요청 내용. */
	private String directCallContent;

}
