package leasecity.dto;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 알림 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Notification implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 알림번호. */
	private Integer notificationNo;

	/** 회원. */
	private Users users;

	/** 임대 요청 번호. */
	private Integer leaseCallNo;

	/** 임대 신청 번호. */
	private Integer leaseRequestNo;

	/** 임대 직접 신청 번호. */
	private Integer leaseDirectNo;

	/** 임대 양도 번호. */
	private Integer leaseTransferNo;

	/** 게시글 번호. */
	private Integer commentNo;

	/** 댓글 인식번호. */
	private Integer replyNo;

	/** 알림날짜. */
	private Date regDate;
}
