package leasecity.dto;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * 질문 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@AllArgsConstructor
@EqualsAndHashCode
public class Question implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 질문글 번호. */
	private Integer questionNo;

	/** 회원. */
	private String userId;

	/** 질문글 제목. */
	private String questionTitle;

	/** 질문글 분류. */
	private String questionCategory;

	/** 질문글 내용. */
	private String questionContent;

	/** 조회 수. */
	private Integer hits;

	/** 질문 등록 날짜. */
	private Date regDate;

	/** 답변 목록. */
	private List<Answer> answersList;

	/**
	 * 생성자.
	 */
	public Question() {
		this.answersList = new ArrayList<Answer>();
	}

}
