package leasecity.dto;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * 회원 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */

@Data
@AllArgsConstructor
@EqualsAndHashCode
public class User implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 아이디. */
	private String userId;

	/** 비밀번호. */
	private String password;

	/** 업체명. */
	private String companyName;

	/** 대표자명. */
	private String representName;

	/** 대표자 연락처. */
	private String representPhone;

	/** 휴대폰 연락처. */
	private String handPhone;

	/** 이메일 주소. */
	private String email;

	/** 주소. */
	private String address;

	/** 알림여부. */
	private String notificationOnOff;

	/** 보유 사이트 / URL. */
	private String url;

	/** 회원가입 날짜. */
	private Date regDate;

	/** 평가점수. */
	private Float evaluation;

	/** 커뮤니티 게시글 목록. */
	private List<Comment> commentsList;

	/** 건설업체 목록. */
	private List<ConstructionCompany> constructionCompanyList;

	/** 중기업체 목록. */
	private List<HeavyEquipmentCompany> heavyEquipmentCompanyList;

	/** 질문 목록. */
	private List<Question> questionsList;

	/** 커뮤니티 댓글 목록. */
	private List<Replys> replysList;

	/** 작업 내역 목록. */
	private List<WorkLog> workLogList;

	/**
	 * 생성자.
	 */
	public User() {
		this.commentsList = new ArrayList<Comment>();
		this.constructionCompanyList = new ArrayList<ConstructionCompany>();
		this.heavyEquipmentCompanyList = new ArrayList<HeavyEquipmentCompany>();
		this.questionsList = new ArrayList<Question>();
		this.replysList = new ArrayList<Replys>();
		this.workLogList = new ArrayList<WorkLog>();
	}
}
