package leasecity.dto;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import lombok.AllArgsConstructor;
import lombok.Data;

/**
 * 회원 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@AllArgsConstructor
public class Users implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 아이디. */
	private String userId;

	/** 비밀번호. */
	private String password;

	/** 대표자명. */
	private String representName;

	/** 대표자 연락처. */
	private String representPhone;

	/** 휴대폰 연락처. */
	private String handPhone;

	/** 이메일 주소. */
	private String email;

	/** 주소. */
	private String address;

	/** 알림여부. */
	private String notificationOnOff;

	/** 보유 사이트 / URL. */
	private String url;

	/** 업체명. */
	private String companyName;

	/** 평가점수. */
	private Float evaluation;

	/** 커뮤니티 게시글 목록. */
	private Set<Comments> commentsSet;

	/** 건설업체 목록. */
	private Set<ConstructionCompany> constructionCompanySet;

	/** 중기업체 목록. */
	private Set<HeavyEquipmentCompany> heavyEquipmentCompanySet;

	/** 알림 목록. */
	private Set<Notification> notificationSet;

	/** 질문 목록. */
	private Set<Questions> questionsSet;

	/** 커뮤니티 댓글 목록. */
	private Set<Replys> replysSet;

	/** 작업 내역 목록. */
	private Set<WorkLog> workLogSet;

	/**
	 * 생성자.
	 */
	public Users() {
		this.commentsSet = new HashSet<Comments>();
		this.constructionCompanySet = new HashSet<ConstructionCompany>();
		this.heavyEquipmentCompanySet = new HashSet<HeavyEquipmentCompany>();
		this.notificationSet = new HashSet<Notification>();
		this.questionsSet = new HashSet<Questions>();
		this.replysSet = new HashSet<Replys>();
		this.workLogSet = new HashSet<WorkLog>();
	}
}
